--------------------------------------------------------
--  Fichier créé - vendredi-mai-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENT
--------------------------------------------------------

  CREATE TABLE "AHMEDBALTI"."AGENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"DATENAIS" VARCHAR2(20 BYTE), 
	"POSTE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
-- Impossible d'afficher le langage DDL TABLE pour l'objet AHMEDBALTI.CELL avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE CELL 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, MAX VARCHAR2(20 BYTE) 
, CURRENTT VARCHAR2(20 BYTE) 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TABLE1_PK ON CELL (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Impossible d'afficher le langage DDL TABLE pour l'objet AHMEDBALTI.CITOYEN avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE CITOYEN 
(
  NUMCIN VARCHAR2(20 BYTE) NOT NULL 
, NOM VARCHAR2(20 BYTE) 
, PRENOM VARCHAR2(20 BYTE) 
, DATEN VARCHAR2(20 BYTE) 
, SEXE VARCHAR2(20 BYTE) 
, ACTIVITE VARCHAR2(20 BYTE) 
, NBRPTS NUMBER 
, NUMREC VARCHAR2(20 BYTE) 
, CONSTRAINT CITOYEN_PK2 PRIMARY KEY 
  (
    NUMCIN 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CITOYEN_PK2 ON CITOYEN (NUMCIN ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Impossible d'afficher le langage DDL TABLE pour l'objet AHMEDBALTI.CONGE avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE CONGE 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, DUREE VARCHAR2(20 BYTE) 
, DATEDEDEMANDE VARCHAR2(20 BYTE) 
, POSTE VARCHAR2(20 BYTE) 
, TYPEDECONGE VARCHAR2(20 BYTE) 
, CONSTRAINT CONGE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CONGE_PK ON CONGE (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Impossible d'afficher le langage DDL TABLE pour l'objet AHMEDBALTI.DETENU avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE DETENU 
(
  ID NUMBER NOT NULL 
, NOM VARCHAR2(20 BYTE) 
, PRENOM VARCHAR2(20 BYTE) 
, SEXE VARCHAR2(20 BYTE) 
, ACTIVITE VARCHAR2(20 BYTE) 
, DESCRIPTION VARCHAR2(20 BYTE) 
, DATEE VARCHAR2(20 BYTE) 
, CIN VARCHAR2(20 BYTE) 
, ID_CELL NUMBER 
, CONSTRAINT DETENU_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX DETENU_PK ON DETENU (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Impossible d'afficher le langage DDL TABLE pour l'objet AHMEDBALTI.ETRANGER avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE ETRANGER 
(
  NUMPASS VARCHAR2(20 BYTE) NOT NULL 
, NOM VARCHAR2(20 BYTE) 
, PRENOM VARCHAR2(20 BYTE) 
, NATIONALITE VARCHAR2(20 BYTE) 
, SEXE VARCHAR2(20 BYTE) 
, AGE NUMBER 
, ACTIVITE VARCHAR2(20 BYTE) 
, ADRESSE VARCHAR2(20 BYTE) 
, CONSTRAINT ETRANGER_PK PRIMARY KEY 
  (
    NUMPASS 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ETRANGER_PK ON ETRANGER (NUMPASS ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Impossible d'afficher le langage DDL TABLE pour l'objet AHMEDBALTI.RECOMPENSE avec DBMS_METADATA tentant le générateur interne.
CREATE TABLE RECOMPENSE 
(
  NUMREC VARCHAR2(20 BYTE) NOT NULL 
, NOMREC VARCHAR2(20 BYTE) 
, NBREX NUMBER 
, DESCRIPTION VARCHAR2(30 BYTE) 
, NBRPTS NUMBER 
, CONSTRAINT RECOMPENSE_PK PRIMARY KEY 
  (
    NUMREC 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RECOMPENSE_PK ON RECOMPENSE (NUMREC ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
REM INSERTING into AHMEDBALTI.AGENT
SET DEFINE OFF;
Insert into AHMEDBALTI.AGENT (ID,NOM,PRENOM,SALAIRE,DATENAIS,POSTE) values ('124','issam','ahmed','2000','04/01/2000','colonel');
Insert into AHMEDBALTI.AGENT (ID,NOM,PRENOM,SALAIRE,DATENAIS,POSTE) values ('125','ali','ahmed','3000','04/01/2000','colonel');
REM INSERTING into AHMEDBALTI.CELL
SET DEFINE OFF;
Insert into AHMEDBALTI.CELL (ID,NAME,MAX,CURRENTT) values ('1','test','0','0');
REM INSERTING into AHMEDBALTI.CITOYEN
SET DEFINE OFF;
Insert into AHMEDBALTI.CITOYEN (NUMCIN,NOM,PRENOM,DATEN,SEXE,ACTIVITE,NBRPTS,NUMREC) values ('33333333','safi','ali','1990/01/08','Homme','eleve','500','5');
Insert into AHMEDBALTI.CITOYEN (NUMCIN,NOM,PRENOM,DATEN,SEXE,ACTIVITE,NBRPTS,NUMREC) values ('14482159','aissa','aissa','2000/01/01','Homme','aa','0',null);
Insert into AHMEDBALTI.CITOYEN (NUMCIN,NOM,PRENOM,DATEN,SEXE,ACTIVITE,NBRPTS,NUMREC) values ('33335566','ouni','nassim','2000/01/07','Homme','eleve','900','35');
Insert into AHMEDBALTI.CITOYEN (NUMCIN,NOM,PRENOM,DATEN,SEXE,ACTIVITE,NBRPTS,NUMREC) values ('22558877','hkimi','ahmed','2000/01/03','Homme','plongeur','24',null);
REM INSERTING into AHMEDBALTI.CONGE
SET DEFINE OFF;
Insert into AHMEDBALTI.CONGE (ID,DUREE,DATEDEDEMANDE,POSTE,TYPEDECONGE) values ('14','14','05/01/2000',null,'Nouvel Ã©lÃ©ment');
REM INSERTING into AHMEDBALTI.DETENU
SET DEFINE OFF;
Insert into AHMEDBALTI.DETENU (ID,NOM,PRENOM,SEXE,ACTIVITE,DESCRIPTION,DATEE,CIN,ID_CELL) values ('4',null,null,'Homme',null,null,'01/01/2000','4875','0');
Insert into AHMEDBALTI.DETENU (ID,NOM,PRENOM,SEXE,ACTIVITE,DESCRIPTION,DATEE,CIN,ID_CELL) values ('2',null,null,'Homme',null,null,'01/01/2000','3333','0');
REM INSERTING into AHMEDBALTI.ETRANGER
SET DEFINE OFF;
Insert into AHMEDBALTI.ETRANGER (NUMPASS,NOM,PRENOM,NATIONALITE,SEXE,AGE,ACTIVITE,ADRESSE) values ('36987458','sakho','mamadou','ivoirienne','Homme','28','etudiant','Tunis');
Insert into AHMEDBALTI.ETRANGER (NUMPASS,NOM,PRENOM,NATIONALITE,SEXE,AGE,ACTIVITE,ADRESSE) values ('56879631','sakho','mamadou','ivoirienne','Homme','28','etudiant','Tunis');
REM INSERTING into AHMEDBALTI.RECOMPENSE
SET DEFINE OFF;
Insert into AHMEDBALTI.RECOMPENSE (NUMREC,NOMREC,NBREX,DESCRIPTION,NBRPTS) values ('15','resto','30','50','0');
Insert into AHMEDBALTI.RECOMPENSE (NUMREC,NOMREC,NBREX,DESCRIPTION,NBRPTS) values ('14','bande d''achat','300','bande','600');
Insert into AHMEDBALTI.RECOMPENSE (NUMREC,NOMREC,NBREX,DESCRIPTION,NBRPTS) values ('17','resto','700','ticket resto','900');
--------------------------------------------------------
--  Constraints for Table CELL
--------------------------------------------------------

  ALTER TABLE "AHMEDBALTI"."CELL" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AHMEDBALTI"."CELL" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "AHMEDBALTI"."CONGE" ADD CONSTRAINT "CONGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "AHMEDBALTI"."CONGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ETRANGER
--------------------------------------------------------

  ALTER TABLE "AHMEDBALTI"."ETRANGER" ADD CONSTRAINT "ETRANGER_PK" PRIMARY KEY ("NUMPASS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "AHMEDBALTI"."ETRANGER" MODIFY ("NUMPASS" NOT NULL ENABLE);
